# php vendor/bin/sfynx-ddd-generator \
# --namespace=PromotionContext \
# --conf-file=/var/www/app/config/generator/entity_offer_2.yml \
# --report-template=default \
# --report-dir=/var/www/src
default:
    namespace: PromotionContext
    cqrs: Offer\Command
    template: default
    widgets:
        presentation:
            widget_coordination:
                class: Form2Coordination
                arguments:
                    - '$workflowHandler'
                extends: Sfynx\CoreBundle\Layers\Presentation\Coordination\Generalisation\AbstractFormController
                options:
                    implements: ~
                    uses: ~
                    traits: ~
                body:
                    - command:
                        design: 'adapter'
                        class: Sfynx\CoreBundle\Layers\Presentation\Adapter\Command\CommandAdapter
                        arguments:
                            - 'new Offer2FormCommand'
                        calls:
                            - [ createCommandFromRequest, [ 'new Offer2FormRequest' ] ]
                    - commandWorkflow:
                        design: 'observer'
                        class: Sfynx\CoreBundle\Layers\Application\Command\Workflow\CommandWorkflow
                        calls:
                            - [ attach, [ 'new OBOffer2EntityEdit' ] ]
                            - [ attach, [ 'new OBOffer2EntityCreate' ] ]
                    - commandHandlerResult:
                        design: 'decorator'
                        class: Sfynx\CoreBundle\Layers\Application\Command\Handler\FormCommandHandler
                        arguments:
                            - '$CommandWorkflow'
                        handlers: [ 'Offer2FormCommandValidationHandler', 'Offer2FormCommandSpecHandler']
                        calls:
                            - [ process, [ '$command' ] ]
                    - codeln1:
                        design: 'code'
                        content: "$this->param->templating = '@Business/Offer/edit.html.twig'"
                    - workflowHandler:
                        design: 'observer'
                        class: Sfynx\CoreBundle\Layers\Application\Common\Handler\WorkflowHandler
                        calls:
                            - [ attach, [ 'new OBOffer2CreateFormData' ] ]
                            - [ attach, [ 'new OBCreateEntityFormView' ] ]
                            - [ attach, [ 'new OBInjectFormErrors' ] ]
                            - [ attach, [ 'new OBOffer2CreateFormBody' ] ]
                            - [ attach, [ 'new OBCreateResponseHtml' ] ]
                    - ResponseHandlerResult:
                        design: 'handler'
                        class: Sfynx\CoreBundle\Layers\Application\Response\Handler\ResponseHandler
                        arguments:
                            - '$WorkflowHandler'
                        calls:
                            - [ process, [ '$commandHandlerResult' ] ]
                    - codeln2:
                        design: 'code'
                        content: "return $responseHandlerResult->getResponse();"
            widget_request:
                class: Offer2FormRequest
                arguments:
                  - 'Sfynx\CoreBundle\Layers\Domain\Service\Request\Generalisation\RequestInterface'
        application:
            widget_cqrs_command:
                class: Offer2FormCommand
                arguments: ~
            widget_cqrs_validator_specification:
                class: Validation\SpecHandler\Offer2FormCommandSpecHandler
                arguments: ~
            widget_cqrs_validator_validation:
                class: Validation\ValidationHandler\Offer2FormCommandValidationHandler
                arguments: ~
            widget_validation_type:
                class: Offer2Type
                arguments: ~
        domain:
            widget_entity: true
            widget_service_class:
                - EntityManager:
                    create: true
                    class: Domain\Service\Offer\Manager\EntityManager
                    arguments: ~
                    comments: ['Layout manager working with entities (Orm, Odm, Couchdb)']
                    extends: Sfynx\CoreBundle\Layers\Domain\Service\Manager\Generalisation\AbstractManager
                    options:
                        implements: ~
                        uses: ~
                        traits: ~
                        methods:
                          - name: 'newFromCommand'
                            comments: ['{@inheritdoc}']
                            arguments: ['Sfynx\CoreBundle\Layers\Application\Command\Generalisation\Interfaces\CommandInterface']
                            visibility: 'public'
                            returnType: 'object'
                            returnParent: true
                          - name: 'buildFromCommand'
                            comments: ['{@inheritdoc}']
                            arguments: ['object $entity', 'Sfynx\CoreBundle\Layers\Application\Command\Generalisation\Interfaces\CommandInterface', 'bool $updateCommand = false']
                            visibility: 'public'
                            returnType: 'object'
                            returnParent: true
                          - name: 'buildFromEntity'
                            comments: ['{@inheritdoc}']
                            arguments: ['Sfynx\CoreBundle\Layers\Application\Command\Generalisation\Interfaces\CommandInterface', 'object $entity']
                            visibility: 'public'
                            returnType: 'Sfynx\CoreBundle\Layers\Application\Command\Generalisation\Interfaces\CommandInterface'
                            returnParent: true
                - OfferCommandRepositoryInterface:
                    create: true
                    class: Domain\Repository\Command\OfferCommandRepositoryInterface
                    type: interface
                - OfferQueryRepositoryInterface:
                    create: true
                    class: Domain\Repository\Query\OfferQueryRepositoryInterface
                    type: interface
            widget_workflow_observer_class:
                - OBOffer2EntityCreate:
                    create: true
                    class: OBOffer2EntityCreate
                    arguments:
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Manager\Generalisation\Interfaces\ManagerInterface'
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Request\Generalisation\RequestInterface'
                    extends: Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Generalisation\Command\AbstractEntityCreateHandler
                    options:
                        implements: ~
                        uses: ~
                        traits: [Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Command\TraitProcess]
                - OBOffer2EntityEdit:
                    create: true
                    class: OBOffer2EntityEdit
                    arguments:
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Manager\Generalisation\Interfaces\ManagerInterface'
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Request\Generalisation\RequestInterface'
                    extends: Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Generalisation\Command\AbstractEntityEditHandler
                    options:
                        implements: ~
                        uses: ~
                        traits: [Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Command\TraitProcess]
                - OBOffer2CreateFormData:
                    create: true
                    class: Domain\Workflow\Observer\Offer\Response\OBOffer2CreateFormData
                    arguments:
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Request\Generalisation\RequestInterface'
                    extends: Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Generalisation\Response\AbstractCreateFormData
                    options:
                        implements: ~
                        uses: ~
                        traits: ~
                        methods:
                          - name: 'process'
                            comments: ['{@inheritdoc}']
                            visibility: 'protected'
                            returnType: 'bool'
                - OBOffer2CreateFormBody:
                    create: true
                    class: Domain\Workflow\Observer\Offer\Response\OBOffer2CreateFormBody
                    arguments:
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Request\Generalisation\RequestInterface'
                      - 'Symfony\Bundle\FrameworkBundle\Templating\EngineInterface'
                      - '$this->param'
                    extends: Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Generalisation\Response\AbstractCreateFormBody
                    options:
                        implements: ~
                        uses: ~
                        traits: ~
                        methods:
                          - name: 'process'
                            comments: ['{@inheritdoc}']
                            visibility: 'protected'
                            returnType: 'bool'
                - OBCreateEntityFormView:
                    create: false
                    class: Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Response\OBCreateEntityFormView
                    arguments:
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Request\Generalisation\RequestInterface'
                      - 'Symfony\Component\Form\FormFactoryInterface'
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Form\Generalisation\Interfaces\FormTypeInterface'
#                      - 'new Offer2Type'
                - OBInjectFormErrors:
                    create: false
                    class: Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Response\OBInjectFormErrors
                    arguments:
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Request\Generalisation\RequestInterface'
                      - 'Symfony\Component\Translation\TranslatorInterface'
                - OBCreateResponseHtml:
                    create: false
                    class: Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Response\OBCreateResponseHtml
                    arguments:
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Request\Generalisation\RequestInterface'
        infrastructure:
            widget_security_parse: true
            widget_infra_class:
                - CommandOfferRepository:
                    create: true
                    class: Infrastructure\Persistence\Adapter\Command\Orm\OfferRepository
                    arguments: ~
                    comments:
                      - 'This class was generated by the Doctrine ORM. Add your own custom'
                      - 'repository methods below.'
                    extends: Sfynx\CoreBundle\Layers\Infrastructure\Persistence\Adapter\Generalisation\Orm\AbstractCommandRepository
                    options:
                        implements: ['Domain\Repository\Command\OfferCommandRepositoryInterface']
                        uses: ~
                        traits: ~
                - QueryOfferRepository:
                    create: true
                    class: Infrastructure\Persistence\Adapter\Query\Orm\OfferRepository
                    arguments: ~
                    comments:
                      - 'This class was generated by the Doctrine ORM. Add your own custom'
                      - 'repository methods below.'
                    extends: Sfynx\CoreBundle\Layers\Infrastructure\Persistence\Adapter\Generalisation\Orm\AbstractQueryRepository
                    options:
                        implements: ['Domain\Repository\Query\OfferQueryRepositoryInterface']
                        uses: ~
                        traits: ~
    mapping:
        x-providers: [orm, couchdb]
        x-entities:
#          Offer:
#            x-fields:
#              id:
#                name: entityId
#                type: id
#                primaryKey: true
#              template:
#                type: integer
#                targetEntity: PromotionContext\Domain\Entity\Template
#                foreignKey: true
#                required: true
          Offer:
            x-fields:
              id:
                type: valueObject
                voName: IdVO
                primaryKey: true
              template:
                type: valueObject
                voName: IdVO
                targetEntity: PromotionContext\Domain\Entity\Template
                foreignKey: true
                required: true
        x-valueObjects:
          IdVO:
            type: Sfynx\CoreBundle\Layers\Domain\ValueObject\IdVO
            x-fields:
              id:
                name: entityId
                type: id
