# php vendor/bin/sfynx-ddd-generator \
# --namespace=PromotionContext \
# --conf-file=/var/www/app/config/generator/entity_offer_6.yml \
# --report-template=default \
# --report-dir=/var/www/src/generator/FormOffer
default:
    namespace: PromotionContext
    cqrs: Offer\Command
    template: default
    indentation: 4
    widgets:
        presentation:
            widget_coordination:
                class: Form6Coordination
                arguments:
                    - '$workflowHandler'
                extends: Sfynx\CoreBundle\Layers\Presentation\Coordination\Generalisation\AbstractFormController
                options:
                    implements: ~
                    uses: ~
                    traits: ~
                body:
                    - updateCommand:
                        design: 'adapter'
                        class: Sfynx\CoreBundle\Layers\Presentation\Adapter\Command\CommandAdapter
                        arguments:
                            - 'new Offer6FormCommand'
                        calls:
                            - [ createCommandFromRequest, [ 'new Offer6FormRequest' ] ]
                    - commandWorkflow:
                        design: 'observer'
                        class: Sfynx\CoreBundle\Layers\Application\Command\Workflow\CommandWorkflow
                        calls:
                            - [ attach, [ 'new OBOffer6EntityEdit' ] ]
                            - [ attach, [ 'new OBOffer6EntityCreate' ] ]
                    - commandHandlerResult:
                        design: 'decorator'
                        class: Sfynx\CoreBundle\Layers\Application\Command\Handler\FormCommandHandler
                        arguments:
                            - '$commandWorkflow'
                        handlers: [ 'Offer6FormCommandValidationHandler', 'Offer6FormCommandSpecHandler']
                        calls:
                            - [ process, [ '$updateCommand' ] ]
                    - codeln1:
                        design: 'code'
                        content: "$this->param->templating = '@Business/Offer/edit.html.twig'"
                    - workflowHandler:
                        design: 'observer'
                        class: Sfynx\CoreBundle\Layers\Application\Common\Handler\WorkflowHandler
                        calls:
                            - [ attach, [ 'new OBOffer6CreateFormData' ] ]
                            - [ attach, [ 'new OBCreateCommandFormView' ] ]
                            - [ attach, [ 'new OBInjectFormErrors' ] ]
                            - [ attach, [ 'new OBOffer6CreateFormBody' ] ]
                            - [ attach, [ 'new OBCreateResponseHtml' ] ]
                    - responseHandlerResult:
                        design: 'handler'
                        class: Sfynx\CoreBundle\Layers\Application\Response\Handler\ResponseHandler
                        arguments:
                            - '$workflowHandler'
                        calls:
                            - [ process, [ '$commandHandlerResult' ] ]
                    - codeln2:
                        design: 'code'
                        content: "return $responseHandlerResult->getResponse();"
            widget_request:
                class: Offer6FormRequest
                arguments:
                  - 'Sfynx\CoreBundle\Layers\Domain\Service\Request\Generalisation\RequestInterface'
        application:
            widget_cqrs_command:
                class: Offer6FormCommand
                arguments: ~
            widget_cqrs_validator_specification:
                class: Validation\SpecHandler\Offer6FormCommandSpecHandler
                arguments: ~
            widget_cqrs_validator_validation:
                class: Validation\ValidationHandler\Offer6FormCommandValidationHandler
                arguments: ~
            widget_validation_type:
                class: Offer6Type
                arguments: ~
        domain:
            widget_entity: true
            widget_service_manager_class:
                - OfferEntityManager:
                    create: true
                    class: Offer\Manager\Tmp6OfferManager
                    arguments: ~
                    options:
                        entity: 'Offer'
            widget_workflow_observer_class:
                - OBOffer6EntityCreate:
                    create: true
                    class: OBOffer6EntityCreate
                    arguments:
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Manager\Generalisation\Interfaces\ManagerInterface'
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Request\Generalisation\RequestInterface'
                    construct:
                        create: true
                        body:
                          - 'parent::__construct($manager, $request);'
                    extends: Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Generalisation\Command\AbstractEntityCreateHandler
                    options:
                        implements: ~
                        uses: ~
                        traits: [Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Command\TraitProcess]
                - OBOffer6EntityEdit:
                    create: true
                    class: OBOffer6EntityEdit
                    arguments:
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Manager\Generalisation\Interfaces\ManagerInterface'
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Request\Generalisation\RequestInterface'
                      - 'bool $updateCommand = false'
                    construct:
                        create: true
                        body:
                          - 'parent::__construct($manager, $request, $updateCommand);'
                    extends: Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Generalisation\Command\AbstractEntityEditHandler
                    options:
                        implements: ~
                        uses: ~
                        traits: [Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Command\TraitProcess]
                - OBOffer6CreateFormData:
                    create: true
                    class: Domain\Workflow\Observer\Offer\Response\OBOffer6CreateFormData
                    arguments:
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Request\Generalisation\RequestInterface'
                    construct:
                        create: true
                        body:
                          - 'parent::__construct($request);'
                    extends: Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Generalisation\Response\AbstractCreateFormData
                    options:
                        implements: ~
                        uses: ['Sfynx\CoreBundle\Layers\Infrastructure\Exception\WorkflowException', 'Exception']
                        traits: ~
                        methods:
                          - name: 'process'
                            comments: ['{@inheritdoc}']
                            visibility: 'protected'
                            returnType: 'bool'
                            body:
                              - 'try {'
                              - "    $this->wfLastData->formViewData['command'] = $this->wfHandler->command;"
                              - "    $this->wfLastData->formViewData['entity'] = $this->wfHandler->entity;"
                              - '} catch (Exception $e) {'
                              - '    throw WorkflowException::noCreatedFormData();'
                              - '}'
                - OBOffer6CreateFormBody:
                    create: true
                    class: Domain\Workflow\Observer\Offer\Response\OBOffer6CreateFormBody
                    arguments:
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Request\Generalisation\RequestInterface'
                      - 'Symfony\Bundle\FrameworkBundle\Templating\EngineInterface'
                      - '$this->param'
                    extends: Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Generalisation\Response\AbstractCreateFormBody
                    options:
                        implements: ~
                        uses: ['Sfynx\CoreBundle\Layers\Infrastructure\Exception\WorkflowException', 'Exception']
                        traits: ~
                        methods:
                          - name: 'process'
                            comments: ['{@inheritdoc}']
                            visibility: 'protected'
                            returnType: 'bool'
                            body:
                              - "$this->wfLastData->body = '';"
                              - 'try {'
                              - "    $this->wfLastData->body = $this->templating->render("
                              - "        $this->param->templating,"
                              - '        ['
                              - "           'entity' => $this->wfHandler->entity,"
                              - "           'edit_form' => $this->wfLastData->form->createView(),"
                              - "           'errors_form' => $this->wfHandler->errors"
                              - '        ]'
                              - '} catch (Exception $e) {'
                              - '    throw WorkflowException::noCreatedViewForm();'
                              - '}'
                - OBCreateCommandFormView:
                    create: false
                    class: Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Response\OBCreateCommandFormView
                    arguments:
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Request\Generalisation\RequestInterface'
                      - 'Symfony\Component\Form\FormFactoryInterface'
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Form\Generalisation\Interfaces\FormTypeInterface'
#                      - 'new Offer6Type'
                - OBInjectFormErrors:
                    create: false
                    class: Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Response\OBInjectFormErrors
                    arguments:
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Request\Generalisation\RequestInterface'
                      - 'Symfony\Component\Translation\TranslatorInterface'
                - OBCreateResponseHtml:
                    create: false
                    class: Sfynx\CoreBundle\Layers\Domain\Workflow\Observer\Response\OBCreateResponseHtml
                    arguments:
                      - 'Sfynx\CoreBundle\Layers\Domain\Service\Request\Generalisation\RequestInterface'
        infrastructure:
            widget_security_parse: true
    mapping:
        x-providers: [orm, couchdb]
        x-entities:
          Offer:
            x-fields:
              id:
                name: entityId
                type: valueObject
                voName: IdVO
                primaryKey: true
              priceTTC:
                type: float
                required: true
              offerType:
                type: id
                foreignKey: true
                required: true
                mapping:
                  relationship: ManyToOne
                  tergetEntity: PromotionContext\Domain\Entity\TypeList
              title:
                type: string
                required: true
        x-valueObjects:
          IdVO:
            type: Sfynx\CoreBundle\Layers\Domain\ValueObject\IdVO
            x-fields:
              id:
                type: id