parameters:
    #
    # JQUERY
    #         
    sfynx.core.config.jquery.grid : 
        grid-table: 'sfynx.core.jquery_manager.gridtable'  
        
    sfynx.core.config.jquery.form : 
        prototype-bytab: 'sfynx.core.jquery_manager.prototypebytabs'
        form-simple: 'sfynx.core.jquery_manager.formsimple'
        
services:
    #
    # configuration of the class manager allowed for the config CMF
    #       
    sfynx.core.cmfconfig:
      class: '%sfynx.tool.manager.config.class%'
      arguments: ['@service_container']
      tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest}      
      calls:
        - [ setConfig, [ 'JQUERY', 'GRID', '%sfynx.core.config.jquery.grid%' ] ]
        - [ setConfig, [ 'JQUERY', 'FORM', '%sfynx.core.config.jquery.form%' ] ]